# This is a basic workflow to help you get started with Actions
# Hashes per Blaze [4462] Hashes
# Commandline Configuration
If you prefer using a Commandline you can still mine Blaze Via the Configuration Details we provide! simply fill your pool details with the ones below. how to do that varies by program, so make sure to look it up incase you have troubles.

Address: SK_Y78mQFZotjeb7J4gHm43l.Oppo
IP: 168.235.86.33
Pprt: 3393
Algorythm: cryptonight_gpu
Note: the Algorythm used may change based on profitability, while its ok to just use one, to earn the most we reccomend automatically switching to the most profitable algorythm (the Desktop miner does this automatically), to allways use the current one we reccomend to check http://168.235.86.33:64080/mine.json atleast once an hour for the current pool to use
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main.yml ]
  pull_request:
    branches: [ main.yml ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
